### ISSUE TITLE
mingw-w64-angleproject deps

### ISSUE THREAD

**Issue by drakkan** [Martchus/PKGBUILDs#12]
It should depend on mingw-w64-crt or mingw-w64-crt-git actually in mingw there is only crt-git

**Comment by Martchus** [comment]
Please note that the PKGBUILDs provided here are meant for building natively under Arch Linux. For MSYS2 mingw-w64 packages checkout [their repository](https://github.com/Alexpux/MINGW-packages). However, the version there is probably very old.

**Comment by drakkan** [comment]
OK, in arch repo there is mingw-w64-crt in the repo you linked and in msys2 on windows there is the git version only, I'm building from msys2 with no cross compilation, probably I'm doing the wrong thing ... I want qt 5.7 with opengl dynamic

**Comment by Martchus** [comment]
You can get Qt 5.7 with dynamic openql by cross compiling under Arch Linux. Don't know whether MSYS has 5.7 and dynamic option yet.

You can not use the Arch Linux `mingw-w64-crt` package or any other native mingw-w64 Arch packages under MSYS2.

**Comment by drakkan** [comment]
Yes I'm rebuilding from arch now, thanks

**Comment by drakkan** [comment]
I did the build from arch linux successfully, anyway when I launch my app if I set QT_OPENGL=desktop all is fine, while if I set QT_OPENGL=angle I get errors like these

`QOpenGLShader::link: D3D compiler module not found.

shader compilation failed:
"D3D compiler module not found.\n"
QOpenGLShader::link: D3D compiler module not found.
D3D compiler module not found.

QOpenGLShaderProgram::uniformLocation( matrix ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( pixelSize ): shader program is not linked
QOpenGLShader::link: D3D compiler module not found.`

I have D3DCompiler_47.dll in the same directory of the app exe, have I to use a specific d3d compiler version? thanks

**Comment by Martchus** [comment]
Not sure. Maybe I did the packaging for the dynamic Qt variant incorrectly. I had to patch the build system to enable the dynamic behavior under Linux because this is by default only covered in the Windows-only configure script.

ANGLE itself is present, I assume? Maybe Dependency Walker helps finding required DLLs by ANGLE or Qt itself (or maybe not because everything works plug-in like).

Does the regular ANGLE version work (I haven't even rebuild it when updating to 5.7.1)? Which versions of ANGLE and Qt do you use exactly?

**Comment by drakkan** [comment]
angle is present and Dependency Walker shows that no dll is missing, I self compiled angle and qt from arch  so I'm using the latest version from aur. I'm not using your binary. Does it work for you/with your binaries? Did you test a qml app with angle? thanks

**Comment by drakkan** [comment]
I did another test today using a sample app that depends on qt and gstreamer (I submitted gstreamer packages to aur too)

If I compile this app using mingw it works fine with opengl but not with angle

If I compile the same app with msvc using the official qt binaries it works with both angle and opengl,

I used the same D3DCompiler_47.dll for both tests

**Comment by Martchus** [comment]
Sorry, I almost forgot this issue. But currently I'm struggling with getting Qt 5.8.0 to work.

> Did you test a qml app with angle?

Actually not, at least not recently.

> I had to patch the build system to enable the dynamic behavior under Linux because this is by default only covered in the Windows-only configure script.

This is from my last answer and I still suspect that I did enabling ANLGE or dynamic OpenGL incorrectly. However, in Qt 5.8.0 those custom patches are no longer required so the issue might be fixed then.

Do you use mingw-w64-qt5-base-dynamic or mingw-w64-qt5-base-angle to test with ANGLE? Does anything work with ANGLE provided by my mingw-w64-angleprojct package (eg. ANGLE samples)?

**Comment by drakkan** [comment]
I tested only mingw-w64-qt5-base-dynamic

I have no hurry this is only an experiment that I'm doing in my free time, I'll wait for Qt 5.8 and when available I'll test angle samples first, thanks!
